### ISSUE TITLE
Create Nativescript Boilerplate Application

### ISSUE THREAD

**Issue by coreyshuman** [Shift3/standards-and-practices#108]
- Mobile app only for now
- Use Latest NS version
- Add the following screens
  - Login (simulated for now)
  - Example List View
- CircleCI
  - Unit Tests

- Create a new repo in Shift3, and then link to it in the nativescript README here.

**Comment by coreyshuman** [comment]
@Basim-Elayan can you provide a link to the repo you're working on?

@kmausolf could you create a similar issue to this for the boilerplate you're doing? Please put it here in S&P, and assign yourself and @ryekerjh. Thanks!

**Comment by Basim-Elayan** [comment]
https://github.com/Shift3/NativeScript-Boilerplate

**Comment by coreyshuman** [comment]
Further progress on this will be addressed in the boilerplates project approved by Chris and Irma.
