### ISSUE TITLE
Flesh out Project Boards

### ISSUE THREAD

**Issue by ryekerjh** [Shift3/standards-and-practices#115]
We need a more thorough process for _how_ the project boards should be set up, and how to manage the repos for our devs and PMs. 
[Here is the current process](https://github.com/Shift3/standards-and-practices/blob/5757e8e3917f0e3916857017d35cf87e22fc8823/git-and-github/project-setup.md)

@carlosvargas graciously volunteered to head this up [here](https://github.com/Shift3/standards-and-practices/pull/114#pullrequestreview-259025949). Thanks @carlosvargas !! 🤣

**Comment by coreyshuman** [comment]
@ryekerjh @carlosvargas 
This process is out of date and no longer correct. Each project should represent an epic, and the content of the board should be kanban-style for tracking issue progress within that Epic.

Open to feedback on this, but I believe this is what Ryeker and I came up with last time we chatted. Please see how Sinclair boards are setup: https://github.com/Shift3/sinclair-scanner-application/projects

Please ignore the fact that @dunlavy is not using the boards even though I've asked him to and put in all the time to set them up for him. =P

**Comment by Karvel** [comment]
Here is an example set of boards following Corey's proposal above.

https://github.com/Shift3/sinclair-scanner-api/projects

**Comment by ryekerjh** [comment]
@coreyshuman @Karvel I am going to move forward with your suggestion and write this up. I'll submit it soon.
