### ISSUE TITLE
Add Vue to list of frontend frameworks

### ISSUE THREAD

**Issue by juliancoleman** [Shift3/standards-and-practices#12]
It works a lot like React, but feels about half the size, and works about half the size. It's a pretty popular framework to use with Laravel stacks.

Also, it's pronounced like "view", Micheal Wallert. Not like "Voo" :smirk:

**Comment by ryekerjh** [comment]
No.

**Comment by juliancoleman** [comment]
@ryekerjh why not?

**Comment by vperezma** [comment]
@ryekerjh remember this repo is to bring in info for our developers from our developers and that includes info about frameworks we might dislike or feel are not adequate for our projects. @juliancoleman my invitation to contribute is still open. If you or Vinson are up for setting up a quick getting started with Vue or quick write up about why Vue is a good choice please feel free to create a PR.

**Comment by juliancoleman** [comment]
@vperezma Sure thing, man!

**Comment by juliancoleman** [comment]
@ryekerjh I'm open to hear about why you feel Vue is not a great framework. I have my `meh` moments with it, but I'm curious also to hear your thoughts. I'm personally a React guy, and believe me when I say I wish I could throw people off the second floor over how much grief React gives me on a daily. Still my daily driver. I guess I've come to accept there will never be a perfect framework. I'm just offering alternatives that scale based on the project size. Obviously I'm not going to use React for a basic website. That's just ridiculous.

**Comment by ryekerjh** [comment]
@juliancoleman Oh, no I was just joking around! Ill keep it professional from here on out. :)

**Comment by juliancoleman** [comment]
I got you, man. I thought it was that I had mentioned Laravel hahaha

**Comment by ryekerjh** [comment]
@juliancoleman LOL, that would def elicit such a response. haha!

**Comment by juliancoleman** [comment]
Hahaha sounds good. Alright, so, most of my time is devoted to finishing up Mission Control. Once I'm done with that, I'll tackle this issue with a PR.

**Comment by michaelachrisco** [comment]
So Im not 100% sure why this issue was closed. 

We still list Vue on our client side frameworks, but the link does not go anywhere: https://github.com/Shift3/standards-and-practices/tree/master/best-practices/client-side/framework

What is everyones opinion on the framework 3 years later?

**Comment by zbyte64** [comment]
Vue is my favorite of the three (Angular, React, Vue) because I find it ergonomic, they have thought about how to make the component easy to understand and provide guidance for common use cases. 

I am not sure if we should concentrate on providing a boilerplate, they vue cli is pretty awesome for adding new services to the project (think `vue-cli add apollo-graphql`.

**Comment by michaelachrisco** [comment]
Thanks for the feedback @zbyte64! Since orderslp uses Vue, we should at least have some general information on the framework. 

I am going to pull in @cobyfielding work on https://github.com/Shift3/standards-and-practices/pull/77 and at least get the READMEs back in.

**Comment by michaelachrisco** [comment]
Added back in basics into this repo. I think we should attempt a boilerplate repo at some point to demonstrate a good living project. Closing.
