### ISSUE TITLE
Lessons learned with upgrading Expo SDK

### ISSUE THREAD

**Issue by Fleury14** [Shift3/standards-and-practices#144]
Hey folks, I just recently completed an SDK upgrade with Expo from 32 all the way to 36. Definitely ran into some issues that I'd like to document just in case anyone else ever has to go through this process in the future.

Where should I put this? Maybe a `lessons-learned` folder?

@ryekerjh @mwallert @carlosvargas - would love to get your input as to where I should place this?

**Comment by ryekerjh** [comment]
@Fleury14 I think `best-practices/native/react-native/expo/upgrade` would work.

**Comment by ryekerjh** [comment]
Also, this is a GREAT idea!
