### ISSUE TITLE
Create standard list of Shift3 labels for Github

### ISSUE THREAD

**Issue by coreyshuman** [Shift3/standards-and-practices#156]
Github allows Organizations to have custom labels which are automatically added to all new projects. I would like to leverage that feature to generate a standard set of labels to be used at Shift3 moving forward. 

Label categories would include:
- QA testing labels per the QA process standard
- Issue priority levels (low priority, high priority, critical)
- Issue categories (bug, enhancement, documentation, discussion, question, etc)
- Status labels (hold, next phase, duplicate, help wanted, wontifx, etc)

Include description for each label.

TODO: Generate the official list in this issue.

**Comment by Karvel** [comment]
I would suggest tweaking the issue category section to match the Karma commit types: `bug`, `chore`, `docs`, `feat`, `refactor`, `test`, `style`. It would make sense to also keep `discussion` and `question`.

**Comment by mwallert** [comment]
I like these suggestions. We have a few created on IFG that we used quite a bit.

`HOLD` or `on-hold`, `client change request`

**Comment by michaelachrisco** [comment]
A common I used is `waiting-for-client`. Useful when the team has completed a task and needs feedback/approval from the clients. Similar to @mwallert `hold`.

**Comment by Karvel** [comment]
Here are the labels I commonly use. I've included both a screenshot to show the colors, and the JSON of the payload the API would need to [add these programmatically](https://developer.github.com/v3/issues/labels/). I left the default initial labels. We would want to add the other labels like `low priority`, `high priority`, `critical`, `hold`, `waiting-for-client`, etc.

![Screen Shot 2020-04-09 at 13 59 34](https://user-images.githubusercontent.com/488032/78940262-6a7e3700-7a6a-11ea-9e28-9e77529fd68e.png)

```json
[
    {
        "name": "acceptance test",
        "color": "f7b054",
        "description": "This is an acceptance test of content on the staging environment"
    },
    {
        "name": "bug",
        "color": "d73a4a",
        "description": "Something isn't working"
    },
    {
        "name": "chore",
        "color": "994fe2",
        "description": "Build and script changes"
    },
    {
        "name": "docs",
        "color": "f49c9e",
        "description": "Provides code or repository documentation; not available to users"
    },
    {
        "name": "duplicate",
        "color": "cfd3d7",
        "description": "This issue or pull request already exists"
    },
    {
        "name": "enhancement",
        "color": "a2eeef",
        "description": "New feature or request"
    },
    {
        "name": "feature",
        "color": "7acc37",
        "description": "New feature or change that directly affects users"
    },
    {
        "name": "good first issue",
        "color": "7057ff",
        "description": "Good for newcomers"
    },
    {
        "name": "help wanted",
        "color": "008672",
        "description": "Extra attention is needed"
    },
    {
        "name": "invalid",
        "color": "e4e669",
        "description": "This doesn't seem right"
    },
    {
        "name": "question",
        "color": "d876e3",
        "description": "Further information is requested"
    },
    {
        "name": "refactor",
        "color": "db906d",
        "description": "Code changes underneath the hood; no difference in user experience"
    },
    {
        "name": "staging",
        "color": "000000",
        "description": "A version of a feature branch to be deployed on a staging environment"
    },
    {
        "name": "test",
        "color": "70a7cc",
        "description": "Code tests only"
    },
    {
        "name": "wontfix",
        "color": "ffffff",
        "description": "This will not be worked on"
    }
]
```

**Comment by coreyshuman** [comment]
@Karvel which project is this so I can add a few more labels? Also, did you extract that JSON or do it by hand?

**Comment by Karvel** [comment]
I've got these in all of my repositories:

https://github.com/Shift3/tulare-court-client
https://github.com/Shift3/boilerplate-client-angular
https://github.com/Shift3/sinclair-scanner-website
https://github.com/Shift3/sinclair-scanner-api

Also, I used the API. I made a readonly token to learn how to use it and got the list using [this endpoint](https://developer.github.com/v3/issues/labels/). Another token with write access could generate the rest.

**Comment by michaelachrisco** [comment]
I appears github how supports organization wide labels: https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-default-labels-for-repositories-in-your-organization

**Comment by michaelachrisco** [comment]
I have applied the following issue templates to all NEW repositories:
![image](https://user-images.githubusercontent.com/398491/93133292-d5701180-f68b-11ea-8602-6f3fdc225599.png)
![image](https://user-images.githubusercontent.com/398491/93133325-e0c33d00-f68b-11ea-80f1-cd71894af6a8.png)

These include:
@Karvel labels here: https://github.com/Shift3/standards-and-practices/issues/156#issuecomment-611750058
@mwallert tags here: https://github.com/Shift3/standards-and-practices/issues/156#issuecomment-610538645
as well as the tags from QA here: https://github.com/Shift3/qa-process-example/issues
and PM and platform level level tags from here: https://github.com/Shift3/row-forge-ns/labels

If anyone would like to make a change, feel free to open a new issue or re-open this one. Closing.
