### ISSUE TITLE
Add more detail on git branches

### ISSUE THREAD

**Issue by michaelachrisco** [Shift3/standards-and-practices#157]
As per discussion with @coreyshuman, we should add more detail on why we chose our particular git branching structure. 

When a developer first makes a git branch, the docs state:
> Create feature/fix/task branches to perform your work in. Include your initials so we keep track of who owns branches easily. For example, if I'm (Corey) working on an bug fix task, I'll create a branch such as cts-fix-uploader.

which does not state what modern GUI based git clients (and some command line clients) do with the git branches. Often, these GUI based tools like gitkraken and sourcetree, will organize branches by the standard `<initial>/<issue#>-<short-description>` format and use the <initial> as part of a folder like structure. It makes things much easier to read and followup with a developer on old branches. 

There is also the standard of `<initial>/<feature>/<issue#>-<short-description>` which has the advantage of showing an overarching milestone or feature in the git branch.

We should decide on which branch structure we like to use and then add the reasoning behind it.

**Comment by michaelachrisco** [comment]
Next steps, I think, is to discuss and find documentation supporting our git branch styles beyond just "it looks better" (although its a good argument).

**Comment by michaelachrisco** [comment]
Gitkraken has some good resources on why you may want to use both standards above as well as the developer initial setup.

https://support.gitkraken.com/git-workflows-and-extensions/git-flow/

**Comment by mwallert** [comment]
I'm a fan of either `<initials>-<issue#>-<short-description>` or `<initials>/<issue#>-<short-description>`, I've been usually the later for awhile. Even if the `/` doesn't do any real good, I like it as a visual separator. I believe @pratimasakinala and @ryekerjh had some docs written up that we followed on a few projects with good success.

**Comment by michaelachrisco** [comment]
@mwallert I am under the same opinion. As long as the issue number and short description are in the branch, usually its fine. Feature might be overkill for most projects (unless its a huge monolith maybe?). I had some questions on why the initials were part of the equation until @dunlavy pointed it out.

**Comment by Karvel** [comment]
I like having the issue number and a short description in the branch name. Feature makes sense to me if a project is making use of epics (when feature means karma category I prefer organizing that through labels). I prefer issue number to initials in the branch name because branches can be reassigned. I'm fine with or without the `/` separator (and I do use a GUI Git client that organizes by directory). I'd prefer issue number before initials, but having them there is more important to me than the order.
