### ISSUE TITLE
Double checking outside links in repo

### ISSUE THREAD

**Issue by michaelachrisco** [Shift3/standards-and-practices#162]
When a README project becomes large, it starts to have links that are broken in some manner. So far, for this project, I have not found any erroneous links. 

There is a way to check automatically if the links are all working via the gem `awesome_bot`. Ive used this in another personal project (here is the CI build): https://github.com/michaelachrisco/Electronic-Interchange-Github-Resources/blob/master/.circleci/config.yml
This is just one way to check the links themselves. 

How do we feel about using the same gem + CircleCI to double check all links?

**Comment by mwallert** [comment]
@michaelachrisco I like this idea and I hope we can find more tools like this to remove other manual checks.

**Comment by michaelachrisco** [comment]
Finally got everything setup on this end. Looks like our master branch has some links that are not going anywhere in this repo. 
https://app.circleci.com/pipelines/github/Shift3/standards-and-practices/1/workflows/901200cd-c0d2-47cb-bd51-8a801bd6c8fd/jobs/1

PR coming soon to fix.

**Comment by michaelachrisco** [comment]
Awesomebot is having issues with internal private links. For example: https://github.com/Shift3/ifg/compare/v0.4.0...v0.5.0 causes awesomebot to fail within standards/code-versioning.md 

Anyone outside of the org that is using this link will not be able to navigate to it. Ill whitelist it for now, but we may want to create a new issue where we discuss having the S/P repo contain private repos within a public interface.

**Comment by coreyshuman** [comment]
This is awesome, the bot was well named!

Is it possible to configure it to ignore local/example URLs such as **http://127.0.0.1** ?

**Comment by michaelachrisco** [comment]
While awesome bot is providing us with some really god feedback, I think we may need to revisit how useful this is failing CircleCI builds and creating a barrier to entry on new documentation. 

What I would like this tool to do is only check and inform, not fail the entire PR if one of the hundreds of links it checks fails. 

A couple of solutions:
1. Take a look at CircleCI cron and have awesome_bot run periodically. That way links are still checked regardless of PR status. 
2. Research a new tool. awesome_bot is working but there might be something else out there with similar purpose.

If anyone has any ideas let me know.
