### ISSUE TITLE
Recommended Reading

### ISSUE THREAD

**Issue by michaelachrisco** [Shift3/standards-and-practices#170]
This is based on a slack conversation. 

Would it be useful to have a page that contains resources/links to common software development patterns? A recommended reading list? Im thinking they should be mostly language agnostic since we have specific pages dedicated to Typescript/Angular/React/etc...

Some example resources:
## Online/ebook format:
* https://refactoring.guru/design-patterns: Helped me out when I was trying to figure out different examples of design patterns in some common languages. Also gives a run down of what the design pattern is and why you may want to use it.
* https://understandlegacycode.com/blog/key-points-of-working-effectively-with-legacy-code/ Good Article on how to deal with Legacy Code in a somewhat sane manner. 

## Dead Tree format:
1. [Design Patterns](https://en.wikipedia.org/wiki/Design_Patterns) : Somewhat old book describing many of the design patterns we see in modern day frameworks. Also gives a more detailed description than some other resources.
2. [Clean Code](https://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882): Somewhat of a classic, its self explanatory. Goes over quite a few topics such as how to deal with crunch, Use Pronounceable names, etc... 
3. [Working Effectively with Legacy Code](https://www.amazon.com/Working-Effectively-Legacy-Michael-Feathers/dp/0131177052): If you have ever had to deal with working with a legacy system, this is the book for you. Probably the most "real life" centered book, it has chapter titles such as: `This Class Is Too Big and I Don't Want It to Get Any Bigger", "I Don't Have Much Time and I Have To Change It" and "I Need to Make a Change, but I Don't Know What Tests to Write".

I have a couple of others in my collection that I could add, but I would like to see if this may be worthwhile? What do you think and what resources have helped you design better software?

**Comment by ryekerjh** [comment]
We talked about doing a reading list/book club type setup before COVID where we would read a chapter a month and get together to talk about it. I know @dunlavy was pretty interested in it, and I was too. I'd be down to do a Google Meet once a month to discuss the CS book of the month!

**Comment by michaelachrisco** [comment]
Im down for it.

**Comment by Karvel** [comment]
Here are my recommendations to throw on the pile:

## Ebook (and maybe physical copy)

- [Refactoring: Improving the Design of Existing Code: Martin Fowler, Kent Beck, John Brant, William Opdyke, Don Roberts, Erich Gamma](https://www.amazon.com/Refactoring-Improving-Design-Existing-Code/dp/0201485672)
A great primer on the benefits of refactoring with practical suggestions given real(ish) code examples.
- [99 Bottles — Sandi Metz](https://www.sandimetz.com/99bottles)
General code mastery book. Goes over OOP principles, along with refactoring suggestions.
- [The Pragmatic Programmer, 20th Anniversary Edition: your journey to mastery by David Thomas, Andrew Hunt](https://pragprog.com/book/tpp20/the-pragmatic-programmer-20th-anniversary-edition)
This is much more on how to handle other aspects of a progamming job: avoiding creep and rot, clarifying requirements, working effectively in a team, and more.Also has a hard cover edition: [The Pragmatic Programmer: your journey to mastery, 20th Anniversary Edition (2nd Edition): Thomas, David, Hunt, Andrew](https://www.amazon.com/Pragmatic-Programmer-journey-mastery-Anniversary-dp-0135957052/dp/0135957052)

## Physical copy only

- [Agile Software Development, Principles, Patterns, and Practices: Martin, Robert C.](https://www.amazon.com/Software-Development-Principles-Patterns-Practices/dp/0135974445)
Goes over Object Oriented Design and SOLID principles in detail. The examples are dated (Java and C++) but the concepts are not.

I wonder if video resources would be good to put here also. Different people learn in different ways. Design Patterns is a phenomenal book but it's very dry.

**Comment by michaelachrisco** [comment]
@Karvel Refactoring is an amazing book. Never heard of 99 Bottles, ill have to take a look.

**Comment by michaelachrisco** [comment]
Found another great list of book here: https://blog.pragmaticengineer.com/my-reading-list/

via this article:
https://blog.pragmaticengineer.com/advice-to-myself-when-starting-as-a-software-developer/

Very good read.

**Comment by thomwise** [comment]
I've started reading this ebook, I'm only on the first chapter and it's not exactly light reading material. But I feel like it will be helpful for anyone doing programming related work:
**A Programmer's Guide to Computer Science: A virtual degree for the self-taught developer**
https://www.amazon.com/gp/product/B07W8BMSKG/ref=kinw_myk_ro_title
