### ISSUE TITLE
Add strict typing to React & React Native reusable components

### ISSUE THREAD

**Issue by ryekerjh** [Shift3/standards-and-practices#184]
We need to add strict typing (with either [Typescript](https://www.typescriptlang.org/docs/handbook/react.html) or [Flow](https://flow.org/en/docs/react/)

**Describe the solution you'd like**
I'd like to implement this with Typescript so that everyone who knows it already can transition to React more easily.

**Describe alternatives you've considered**
Flow is easier to set up with React, but it's also one more thing to learn.

**Additional context**
This is long-overdue and needs to be done asap.

**Comment by michaelachrisco** [comment]
This is a great topic. I have no strong opinions but I personally gravitate towards using typescript if only for the OO style of work. But this may not translate well over the entire org?

Flow is easy to set up via CircleCI (just `yarn flow` and away you go) and the error statements are usually pretty self explanatory. Its made React and state management a bit more manageable.

**Comment by ryekerjh** [comment]
I agree, and I hope that it'll cause more devs to add to our reusable components collection!
