### ISSUE TITLE
Lesser known git commands

### ISSUE THREAD

**Issue by michaelachrisco** [Shift3/standards-and-practices#192]
**Lesser known git commands**
I noticed a lack of some less used but useful git commands within `standards-and-practices/standards/branching.md`
We may also want a new page on git commands in particular? What does everyone think?

**Proposed additions**
I would like to add the following git commands to the list:
1. git stash: I use `git stash` everyday to switch code that needs to be temporarily stored away for a new branch. This will include the `stash` and `pop` commands. https://git-scm.com/docs/git-stash
2. git hooks: When you need to run tests automatically every time a git commit is made, this is an excellent recommendation. Ive found it better for bigger projects that have lots of git references and library dependencies. https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks
3. git reflog: Almost never used (for good reason) until something goes wrong with a merge or rebase. Its a great tool to figure out what git is actually doing in the background. I would like to include it, if just to make people aware of it. https://git-scm.com/docs/git-reflog

Can anyone else think of any other git commands that are useful to everyday development?

**Comment by kmausolf** [comment]
I agree that these commands are useful, in addition to the ones currently in `branching.md`.  From my perspective, however, `branching.md` should concern itself with branching patterns that Shift3 has found to be effective for facilitating a smooth workflow.  If we're going to take on Git CLI tutorials, we should do so in a separate file (perhaps a `gitcli.md`?).

For example, when I was sharing our branching standards with the Navigate Client Portal team, we found that Shift3's pattern of maintaining three top level branches, `master`, `staging`, and `development`, along with feature branches based on `development` to be helpful in organizing the project.  The Git CLI section of that file felt a bit out of place, and may be better served as its own document.

**Comment by michaelachrisco** [comment]
> I agree that these commands are useful, in addition to the ones currently in `branching.md`. From my perspective, however, `branching.md` should concern itself with branching patterns that Shift3 has found to be effective for facilitating a smooth workflow. If we're going to take on Git CLI tutorials, we should do so in a separate file (perhaps a `gitcli.md`?).
> 
> For example, when I was sharing our branching standards with the Navigate Client Portal team, we found that Shift3's pattern of maintaining three top level branches, `master`, `staging`, and `development`, along with feature branches based on `development` to be helpful in organizing the project. The Git CLI section of that file felt a bit out of place, and may be better served as its own document.

I agree, a gitcli.md or UsefulGitCommands.md might be a better place to put these other commands. Maybe even some git hooks?

**Comment by kmausolf** [comment]
I'd love to learn more about Git hooks.  That'd be great!

**Comment by michaelachrisco** [comment]
> I'd love to learn more about Git hooks. That'd be great!

Githooks are so useful before you commit something XD. Ill add in a few that I use and see what everyone thinks.
Anyone else using githhooks?

**Comment by michaelachrisco** [comment]
Some interesting git aliases here: https://medium.com/hackernoon/lesser-known-git-commands-151a1918a60

**Comment by michaelachrisco** [comment]
I'm starting on githooks as a concept and attempting to make it work with node wince I assume that is what most of the projects are using ATM.

Found a somewhat dated resource here: https://medium.com/@satya164/improving-nodejs-workflow-with-git-hooks-40996830619f that has **human readable** descriptions on the different hooks you can use in node.

Does anyone use githooks in their workflow? What do you think about this subject?
