### ISSUE TITLE
Example bug template within S/P repo

### ISSUE THREAD

**Issue by michaelachrisco** [Shift3/standards-and-practices#201]
**Bug template**
We do not have a bug template within this repository, but we do have them within other internal projects. Dealing with bugs is an every day occurrence for us, so having a standard template would be useful.

**Describe the solution you'd like**
We should create(or steal) a good GitHub bug template to use in other projects. It would be ideal if we can use a known good one that is already within one of our internal projects.

**Comment by Karvel** [comment]
I've been using this: https://github.com/Shift3/boilerplate-client-angular/blob/development/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by michaelachrisco** [comment]
> I've been using this: https://github.com/Shift3/boilerplate-client-angular/blob/development/.github/ISSUE_TEMPLATE/bug_report.md

Looks perfect for our needs. Do you mind adding it to this repo?
