### ISSUE TITLE
Master/Main branches on GitHub

### ISSUE THREAD

**Issue by michaelachrisco** [Shift3/standards-and-practices#206]
**GitHub master branch to main**
[On October 1st](https://github.com/github/renaming#on-october-1-2020-newly-created-repositories-will-default-to-main), GitHub will default any new repositories  `master` branches to `main`.

This change will most likely cause issues with our linked READMEs and CircleCI configurations on this repo as well as any new repo that is created.

**Potential Solutions**
We should probably be proactive and start a PR changing all instances of `master` to `main` before October 1st. This will alleviate some of the pain we will be feeling on that week.

An alternative would be to [opt out](https://github.com/github/renaming#on-october-1-2020-newly-created-repositories-will-default-to-main) to give us some time to make the changes. It will require us to make sure every repo has a default branch and/or [setting up our organization](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-the-default-branch-name-for-repositories-in-your-organization) to use master as the default branch for the time being. I think I like this approach more because then we wont need to scramble. 

This seems to be the way the industry is moving so we would probably make the change at some point. Thoughts?

**Comment by michaelachrisco** [comment]
As per conversation with Corey, we should try out a circleci sample project to see how well circleci takes the new default branch and what might be needed to continue with these changes.

**Comment by michaelachrisco** [comment]
As per [documentation](https://circleci.com/docs/2.0/configuration-reference/#branches), It appears that if a branch is hard set, then it will run via that default branch. I dont see this as an issue on our existing repos, but we should probably document just in case.

**Comment by mwallert** [comment]
I would have to check on this manually but I believe most repos have a default branch set `dev | develop | development` so like you said we should be okay. @michaelachrisco @coreyshuman This seems like a worthy addition to the news letter and or even a team blast?

**Comment by michaelachrisco** [comment]
I created a repo that has more detail on the risk above and a solution:
https://github.com/Shift3/MasterToMainRepo/issues/1

This specifically looks at handling CircleCI. If a repo changes (or starts out with) the `master` branch being the default branch, then the deploy script will work as per CircleCIs own documentation. If this branch switches to `main`, the script no longer works and the deploy silently breaks. The fix is to make sure when using CircleCI workflow operations, to assign `main` anywhere where the `master` branch is located.

This is just one example. Any npm/pip/crate/gem/etc... that has hard set references that include the master branch may contain this risk as well. Some fix would have to be applied if the package maintainer uses `main`. Hopefully, there are not a huge number of repos that have hard set package manager branches embedded within the build files...

**Comment by michaelachrisco** [comment]
> I would have to check on this manually but I believe most repos have a default branch set `dev | develop | development` so like you said we should be okay. @michaelachrisco @coreyshuman This seems like a worthy addition to the news letter and or a team blast?

I think the news letter and team blast the week that the changes occur are great ideas.

Something like C/P Githubs official docs on the matter:
```
Please be aware that on October 1, 2020, any new repositories you create will use main as the default branch, instead of master. This change does not impact any of your existing repositories: existing repositories will continue to have the same default branch they have now.

Please also take a look at your dependencies through your package managers to make sure none of the new changes effect your ongoing projects.For more information: https://github.com/github/renaming#from-master-to-main
``` 

Feedback is welcome on this. We may want more to this to prevent misconceptions.

**Comment by michaelachrisco** [comment]
Also very similar: I believe if this is the direction Github is taking, then we should also change this repo to have `main` as the default branch instead of `master`. What does everyone think?

**Comment by mwallert** [comment]
@michaelachrisco Yeah if this is the standard they are seeing it makes sense to follow suit. At first my reaction was:

`No, the base branch is master. Its always been master, why change it.`

After letting it sit I think the change is fine and `main` is just as good as master. I hope I'm not already turning into a grumpy old developer :joy:

**Comment by kmausolf** [comment]
@michaelachrisco It's a great idea.  I dislike the whole `master/slave` naming dynamic that has existed for too long in the software industry.  Seems like a fairly easy change too!

**Comment by michaelachrisco** [comment]
:older_man: :older_adult: :older_woman: <- grumpy old developers. 

Love that GitHub has these emojis. 
@mwallert I felt the same way, but if it makes someones day just a little bit better then its worth doing. Plus we want to be _Standard_ definitely on the Standard and Practices repo.

Alright then, when October rolls around, ill change this to main unless anyone else has any objections.
