### ISSUE TITLE
Create section to track Workshops

### ISSUE THREAD

**Issue by coreyshuman** [Shift3/standards-and-practices#212]
**Is your feature request related to a problem? Please describe.**
We've had our first workshop, now we need somewhere to document those!

**Describe the solution you'd like**
We should add a landing page for workshops, similar to our presentation page seen here:
https://github.com/Shift3/standards-and-practices/blob/master/presentations/README.md

We should also link it in the main readme (same as presentations):
https://github.com/Shift3/standards-and-practices#meetings-are-now-split-into-two-types

**Additional context**
Recording link: https://playback.lifesize.com/#/publicvideo/ea03e55d-c5ee-4df6-87ff-4a1cd0001842?vcpubtoken=d3cc101d-0119-4336-ade8-542818722690
Repository: https://github.com/Shift3/refactoring-workshop

**Comment by michaelachrisco** [comment]
If no-one is picking this up, ill take a look.
