### ISSUE TITLE
Proposal:  S&P Wiki

### ISSUE THREAD

**Issue by kmausolf** [Shift3/standards-and-practices#225]
**Is your feature request related to a problem? Please describe.**
There's so much valuable information in the S&P repo now that it's a bit difficult to know what topics are covered by the repo without digging through every file and reading every README.  It's a bit daunting to new users and limits engagement.

**Describe the solution you'd like**
We can present this data in a digestible format using a GitHub Wiki.  Adding a Wiki would allow us to "flatten" the tree of folders and markup files down to a searchable, menu-navigable user interface.  Most, if not all, of our employees have used a Wiki before, and have been primed to consume information in that format.

**Describe alternatives you've considered**
We could also leave things the way they are.  There are some drawbacks to adding a Wiki, which I'll discuss below.

**Additional context**
If we were to add a Wiki feature, we would need to add an additional step to our review and acceptance process: updating the Wiki.  Unfortunately, the Wiki cannot be synchronized with our extant markup files, so manual updating would be necessary (as far as I know!).  I think the extra lift would be worth the effort, and would contribute to getting more folks up to speed on our standards and practices.  Let me know what you all think!

**Comment by michaelachrisco** [comment]
@kmausolf  I know we started in on creating some wiki pages, but with all the changes lately I never followed up. Are you still looking at working on this? I would love to discuss the idea and take from other wikis that seem to be used in our other repos :)

**Comment by kmausolf** [comment]
@michaelachrisco Now that I've put more thought into it, the Wiki might not be good for a rapidly evolving repo like this one.  Since there does not appear to be any sort of automation for the Wiki, it would need to be maintained parallel to the standards repo, allowing for it to quickly fall out of date and become secondary to the actual standards documents.

**Comment by michaelachrisco** [comment]
Im going to close this one, as per discussion above.
