### ISSUE TITLE
root readme update

### ISSUE THREAD

**Issue by benreckas** [Shift3/standards-and-practices#23]
Hey everyone, I'd love to contribute to something open source like this, but in it's current state it's hard to know where to begin since I don't work for Bitwise/Shift3. 

I'm thinking the root readme could be updated with a linked article on how to contribute to this repo specifically. A simplified version of [Ryeker's contributing doc](https://github.com/Shift3/standards-and-practices/blob/master/client-side/conventions/commits.md) or [Corey's current PR](https://github.com/Shift3/standards-and-practices/pull/22). 

It should also have a section for how and when to submit issues, and maybe a brief code of conduct.

Finally, there's a few broken markdown styles that could be fixed. Spaces needed between hashtag and headers to display properly, and the markdown cheat sheet link can be shortened.

**Comment by vperezma** [comment]
Thanks for your interest @benreckas. We will get those up and/or updated soon.

**Comment by vperezma** [comment]
this is complete with a555910 and c412306. Closing.
