### ISSUE TITLE
Local by Flywheel Workflow Processes

### ISSUE THREAD

**Issue by alejandroxsx** [Shift3/standards-and-practices#233]
Certain processes of using flywheel have not been documented. 
Most particularly updating your local database to be current with the dev server. 

This will ensure plugins, pages, copy, and images are consistent amongst all developers. 
This will also ensure that local repos don't get corrupted as this can happen if steps aren't performed in a certain order 

I'd like to write out the process of updating your local database, with steps written in chronological order.

**Comment by michaelachrisco** [comment]
As per https://github.com/Shift3/standards-and-practices/pull/234#issuecomment-765696701, manually closing this one. Thanks for the docs @alejandroxsx !
