### ISSUE TITLE
Imrpove Docs around .github folder and its function

### ISSUE THREAD

**Issue by michaelachrisco** [Shift3/standards-and-practices#258]
**Is your feature request related to a problem? Please describe.**
We currently have very little docs in the way of describing the `.github` folder and its function within our repos. 

**Describe the solution you'd like**
We should expand the docs to include this folder and its purpose. We should also look into adding the Epic template we are using in the boilerplate projects to this repo, so any new repos are capitalizing on Github Epics. 

**Additional context**
(related to a conversation with @fluturecode)
We should include screenshots such as:
<img width="806" alt="Screen Shot 2021-04-06 at 5 10 31 PM" src="https://user-images.githubusercontent.com/398491/113902835-2c067f80-9785-11eb-9bad-a545711bf6dc.png">

**Comment by Karvel** [comment]
The `.github` folder is also where GitHub Actions and the [CODEOWNERS](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) files would live, if a project has them.

You can see an example of a repo that has all of these [here](https://github.com/Shift3/tulare-court-client/tree/development/.github).

**Comment by michaelachrisco** [comment]
> The `.github` folder is also where GitHub Actions and the [CODEOWNERS](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) files would live, if a project has them.
> 
> You can see an example of a repo that has all of these [here](https://github.com/Shift3/tulare-court-client/tree/development/.github).

Excellent point. Most of our new repos have a CODEOWNERS file, but we need to make sure that is also part of the docs.

**Comment by michaelachrisco** [comment]
As per conversation via slack, Marco wants to take a look at this one.
