### ISSUE TITLE
React VSCode tooling

### ISSUE THREAD

**Issue by michaelachrisco** [Shift3/standards-and-practices#261]
**Is your feature request related to a problem? Please describe.**
React can be a bit difficult to debug using traditional `console.log`(s) and we dont currently have a reference to common debug tooling within the S&P repo.

**Describe the solution you'd like**
We should have react based debug tooling present within the repo. 
https://code.visualstudio.com/docs/nodejs/reactjs-tutorial helped set up debugging in an internal meeting.

**Comment by michaelachrisco** [comment]
Im thinking the reference should go somewhere around here: https://github.com/Shift3/standards-and-practices/tree/main/best-practices/client-side/framework/react

**Comment by michaelachrisco** [comment]
If anyone wants to jump in on this, I would be super grateful!

**Comment by Endtry** [comment]
Hey Michael, this is on my radar. I’ll see if I can get you the assistance
you needed.

Thanks,

**Comment by kmausolf** [comment]
Have we tried React Devtools?  Seems like the best option available for debugging component state, props, etc.

Chrome Extension:
https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en

Guide to using RDT:
https://www.digitalocean.com/community/tutorials/how-to-debug-react-components-using-react-developer-tools

**Comment by michaelachrisco** [comment]
> Have we tried React Devtools? Seems like the best option available for debugging component state, props, etc.

I think so, if its the same as here: https://github.com/Shift3/standards-and-practices/tree/main/best-practices/client-side/framework/react#helpful-react-development-web-plugins 

We don't have any docs on how to _use_ them though. The guide that you referenced would be an excellent addition in my opinion!
