### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by B12Howard** [Shift3/standards-and-practices#264]
## Expected Behavior

When you click on the Link it should re-direct to [https://github.com/Shift3/standards-and-practices/blob/main/standards/qa-process.md](https://github.com/Shift3/standards-and-practices/blob/main/standards/qa-process.md)

## Actual/Current Behavior

When you click the Link it re-directs to [https://github.com/Shift3/standards-and-practices/blob/main/processes/qa-process.md](https://github.com/Shift3/standards-and-practices/blob/main/processes/qa-process.md)

## Steps to Reproduce the Problem

  1. Go to https://github.com/Shift3/standards-and-practices/tree/main/standards#qa-process
  2.  Click QA Process

**Comment by JGustavo11** [comment]
When you click the Link it re direct to (the error)
https://github.com/Shift3/standards-and-practices/blob/main/processes/qa-process.md

When it should be re directed to
https://github.com/Shift3/standards-and-practices/blob/main/standards/qa-process.md

**Comment by B12Howard** [comment]
Changed wording to be more inline with your suggestions

**Comment by michaelachrisco** [comment]
Thanks @B12Howard and @JGustavo11 for bringing this up! I can confirm this is totally an issue. We should also see if the broken link is being used within the app elsewhere. Unfortunately, we whitelisted internal links when we check links with `awesome_bot`.

I would be super appreciative if one of you would create the fix.

**Comment by B12Howard** [comment]
@michaelachrisco I submitted a fix. How would you see if the broken link is used in other places? For me, this was practice doing a pull request using Bitwise's standards, per the automated email
