### ISSUE TITLE
Add SCSS or LESS to CSS folder

### ISSUE THREAD

**Issue by ryekerjh** [Shift3/standards-and-practices#28]
Add S3 standards for writing CSS precompilers

**Comment by michaelachrisco** [comment]
@ryekerjh I see this was added a while back:
https://github.com/Shift3/standards-and-practices/commit/206f5898d0b537fc46e182c17ff469338ecd1e7b

but was removed a while back. Do you think it would be useful to add this README back in?

**Comment by michaelachrisco** [comment]
@ryekerjh Are we safe to close this one?
