### ISSUE TITLE
add frameworks to server-side

### ISSUE THREAD

**Issue by juliancoleman** [Shift3/standards-and-practices#3]
I think it would be a great idea to drill down some backend frameworks that are not only modern, but also provide an education to further develop the skills of each developer. Some frameworks that come to mind...

```
Ruby

- Rails

Python

- Django

Node

- Hapi
- Express
- Koa
- MEAN
```

Anyone can get a Ruby education by building a small Jekyll site for a `gh-pages`. Django will be a sinch to learn, especially if taught by @dmpayton. Node, unfortunately offers many solutions, but are wonderful to learn, no doubt. `Hapi` is a framework I'm particularly fond of, and have worked with a buddy to develop our own simple REST API that is not only easy to extend, but has user auth built right in. `Express` is incredibly common to use. While I have my opinions against `Express`, it does prove to be a great framework for getting APIs up and running with little learning curve and extensive functionality, and is perfect for any team project, and I'm happy to use this on another project. `Koa` is an evolution of Express that uses generator functions for its middleware stack (see [here](https://bramanti.me/working-with-koa-js/)). `MEAN` stacks, we teach in Geekwise, and is widely adopted. That's really all I can say about that.

**Comment by vperezma** [comment]
@juliancoleman that's a great idea. After @patrickPatterson finishes adding these directories can you, if you have time, add some facts or anything you feel necessary to the Hapi or any other directory? I would really like to have as many people contribute to this repo as possible.

**Comment by juliancoleman** [comment]
I'd be more than happy to help contribute on my downtime.

**Comment by patrickPatterson** [comment]
directories added
