### ISSUE TITLE
Add Docker Documentation

### ISSUE THREAD

**Issue by benreckas** [Shift3/standards-and-practices#34]
I'm not sure how commonly Docker is being used in current development projects at Shift3, but it seems like it's picking up steam. I know the current cohort is planning on using it for the credit union app. It also seems like there's only a handful of developers in the building that have a good grasp on it.

Docker's own documentation isn't very good, so this seems like it could be beneficial for everyone. Any thoughts? I wouldn't mind doing a first draft of some common Docker commands and Docker file setup if you like.

**Comment by cobyfielding** [comment]
I think a good start might be to create various docker environments like we do with vagrant scripts.  They will probably need their own individual documentation (at least for commands).  I have a base setup for a docker environment I use, but the documentation would be pretty specific to that environment . A nice wiki on setting up docker environments from scratch and how to add them to the organization (I think this is what you are suggesting) would be a great resource.

**Comment by zbyte64** [comment]
Started a `docker` branch with some examples. Currently I have it filed under `client-side/tools/docker/` but I am not sure if that is appropriate.

**Comment by mwallert** [comment]
I have a branch locally where I had Docker in the root since we can use it on both server and client but we can leave that up to discussion. I like the node example and I was just creating a readme for setting up Docker. I'll push the branch up and see if we can't merge everything together.
