### ISSUE TITLE
add mobile browsers to client-side browser list

### ISSUE THREAD

**Issue by juliancoleman** [Shift3/standards-and-practices#5]
There's no doubt mobile navigation is a huge deal. Most of the time, there seems to be a lack of support, or perhaps more properly put, mobile browsers are having a hard time keeping up with modern technologies. Perhaps this could be a discussion of polyfills, frontend framework support, CSS attribute prefixing provided by `caniuse`, or even CSS variable support for that matter.

**Comment by patrickPatterson** [comment]
@juliancoleman i currently have browser broken up by name, would you have the information above under each browser name or under a "mobile" section
