### ISSUE TITLE
Angular spin up guide

### ISSUE THREAD

**Issue by ryekerjh** [Shift3/standards-and-practices#57]
We need a basic .md for:
- [ ] Installing ng globally 
- [ ] Spin up Angular projects 
- [ ] Creating builds
- [ ] Deploy to staging
- [ ] Deploying to production

**Comment by coreyshuman** [comment]
I suspect the right place for this to live will be within our Angular boilerplate now that it is underway.

**Comment by michaelachrisco** [comment]
Im going ahead and closing since we now have an angular boilerplate that is being used.
