### ISSUE TITLE
SQL Documentation

### ISSUE THREAD

**Issue by ryekerjh** [Shift3/standards-and-practices#59]
Write docs for setting up:
- [x] Postgres
- [x] MSSQL
- [x] MySql

**Comment by michaelachrisco** [comment]
@ryekerjh Ive always thought that Digital Ocean had some of the better docs regarding the installation process on the Linux side: https://www.digitalocean.com/community/tutorial_collections/how-to-install-and-use-postgresql Maybe we can start with that?

**Comment by michaelachrisco** [comment]
I am thinking for MSSQL, we could go over how to create it and which version one should chose for a project via:
1. Developer edition
2. Express 
3. MS Server

I am also thinking Microsoft own documentation may be the best starting point for this: 
https://www.microsoft.com/en-us/sql-server/sql-server-downloads
They even have a docker instance.

Thoughts? What has been the hardest part of setting up a MSSQL instance in past projects?

Would we also want to expose the developer to SSMS at the same time or in a separate page?

**Comment by coreyshuman** [comment]
Generally if we're using MSSQL, it's because a client is self-hosting their infrastructure. In those cases we would be connecting to SQL Server in a Windows environment, often on a private network through a VPN.

I think we should hit this from two angles:
- If you're developing on Windows, for Windows, use the latest SQL Server Developer edition and SSMS (or dbeaver).
- If you're developing NOT on Windows, or not FOR windows, use a dockerized MSSQL instance (and SSMS or dbeaver).

How do those sound as starting points?

**Comment by coreyshuman** [comment]
We should also include resources for T-SQL. It's got quite a few syntactical differences and additional features compared to the Postgres SQL flavor, which would be good to know about if you're going from one to the other.

**Comment by michaelachrisco** [comment]
> We should also include resources for T-SQL. It's got quite a few syntactical differences and additional features compared to the Postgres SQL flavor, which would be good to know about if you're going from one to the other.

Thats a good idea. MSSQL, PostgresSQL, MySQL, Oracle, DB2 ....all have slightly different syntax. Im wondering if that should be its own issue as well, since this issue is about the setup process.

**Comment by michaelachrisco** [comment]
> Generally if we're using MSSQL, it's because a client is self-hosting their infrastructure. In those cases we would be connecting to SQL Server in a Windows environment, often on a private network through a VPN.
> 
> I think we should hit this from two angles:
> 
>     * If you're developing on Windows, for Windows, use the latest SQL Server Developer edition and SSMS (or dbeaver).
> 
>     * If you're developing NOT on Windows, or not FOR windows, use a dockerized MSSQL instance (and SSMS or dbeaver).
> 
> 
> How do those sound as starting points?

Sounds like some good points. The only thing is MSSQL now runs naively on Linux, so a developer could create a localized version of MSSQL and hook into that. Or are we trying to push more docker-ized setups within projects?

I've done both in the past and both are pretty easy to set up as long as you follow Microsoft's instructions to the letter.

**Comment by Karvel** [comment]
It might still be worth dockerizing MSSQL. For the .NET **Core** projects I've done at Shift3, it has been convenient to have the database dockerized, because it allows for portability and development on multiple architectures, including Windows. It's nice to have the option, especially since new developers might join a project and not develop only on Windows. Obviously, this refers to Core and not Framework.

**Comment by Karvel** [comment]
Also, the [Shift3 dotfiles project](https://github.com/Shift3/laptop) sets up PostgresSQL (and Mongo). Many new hires are installing that as it is part of the onboarding process. It's worth including reference to it since it takes care of Postgres on Macs and (many varieties of) Linux.

**Comment by michaelachrisco** [comment]
For the docker solution, I started to make some instructions, but then ran across the official docs here: 
https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-docker-container-deployment?view=sql-server-ver15&pivots=cs1-bash

Ill be honest, they are pretty good and no real issues getting it up and running for both 2017 and 2019 versions. 

I am thinking of just adding that link to Github like we did with all the other resources on best-practices/database/README.md

and then making a separate pages describing the differences between the syntax.

**Comment by michaelachrisco** [comment]
I believe setting up SQL is complete. I believe we can move on to T-SQL and other referenced projects.
