### ISSUE TITLE
NORMALIZE docs

### ISSUE THREAD

**Issue by ryekerjh** [Shift3/standards-and-practices#60]
Write docs for setting up Normalize

**Comment by michaelachrisco** [comment]
@TomAlperin and @Endtry Do you happen to know what @ryekerjh was referencing here?

**Comment by ryekerjh** [comment]
> @TomAlperin and @Endtry Do you happen to know what @ryekerjh was referencing here? 

There was a sql ORM that we developed in house that needed docs. U can probably just remove this issue since y'all dont  really use that anymore
