### ISSUE TITLE
Write docs for Node.js

### ISSUE THREAD

**Issue by ryekerjh** [Shift3/standards-and-practices#63]
basic spin-up guide for node.js as a server.

**Comment by michaelachrisco** [comment]
@ryekerjh Since we are working on the boilerplate project, how do you feel about us referencing the project for new node builds?

**Comment by michaelachrisco** [comment]
I am tempted to add a link to our node boilerplate instead of full blown docs for anonymous node server builds. There are quite a few good practices we added to the boilerplate that already come with a huge amount of docs.

**Comment by michaelachrisco** [comment]
Closing this one out, our node boilerplate is now where we look for a spin up guide.
