### ISSUE TITLE
Basic Ruby Spin up

### ISSUE THREAD

**Issue by ryekerjh** [Shift3/standards-and-practices#64]
Write a markdown for basic Ruby spin up at shift3

**Comment by ryekerjh** [comment]
@DropsOfSerenity Hey, look! we were _just_ talking about this in our FF meeting!! No time like the present 🕐

**Comment by michaelachrisco** [comment]
On the ruby side, Ive had some luck using [rubocop](https://github.com/rubocop-hq/rubocop). Ive found it works pretty well with plain ruby or ruby on rails projects in the past. 

Example here: https://github.com/westernmilling/gman-services/blob/master/.rubocop.yml

Not sure if this is outside of the current scope or not, but thought I would add.

**Comment by michaelachrisco** [comment]
@DropsOfSerenity Does the shop use ruby (and or rails) for any on going projects? Im looking at closing out some old issues.
