### ISSUE TITLE
NativeScript writeup

### ISSUE THREAD

**Issue by ryekerjh** [Shift3/standards-and-practices#66]
Taken from notes from @FlavioShift3 's presentation

**Comment by FlavioShift3** [comment]
- NativeScript: https://www.nativescript.org/
- Documentation: https://docs.nativescript.org/
- UI: https://www.nativescript.org/ui-for-nativescript 
- Playground: [https://play.nativescript.org](https://play.nativescript.org/?_ga=2.234097438.1027288421.1557440601-1272203479.1537481082)

- Market place: https://market.nativescript.org/
- Sign in to slack community: https://www.nativescript.org/slack-invitation-form
- Angular implementation tutorial: [https://docs.nativescript.org/angular/start/introduction](https://docs.nativescript.org/angular/start/introduction?_ga=2.154685112.1027288421.1557440601-1272203479.1537481082)
- Sidekick tool: [https://www.nativescript.org/nativescript-sidekick](https://www.nativescript.org/nativescript-sidekick?_ga=2.188359464.1027288421.1557440601-1272203479.1537481082)

**Comment by coreyshuman** [comment]
@Basim-Elayan @dunlavy @FlavioShift3 Please take a look at what we have in the Nativescript README, let's make a list of additional topics we would like to add.

**Comment by coreyshuman** [comment]
@Basim-Elayan @dunlavy @FlavioShift3 ping. Let's not wait so long that we forget all the lessons learned from Row Forge. Please add notes here for any topics you would like to see turned into write ups/ examples/ etc.

**Comment by dunlavy** [comment]
Will do.  Adding a reminder for myself in Slack.

**Comment by stephengtuggy** [comment]
See Google doc for Release Process SOP Draft here: https://docs.google.com/document/d/1ni4BLrsZwjKwgYXLNaNQQhFu5lQSiU54r5voY_58uCs/edit?usp=sharing

**Comment by michaelachrisco** [comment]
Hello everyone, is this still being worked on? 
https://github.com/Shift3/standards-and-practices/blob/master/best-practices/native/nativescript/README.md

**Comment by FlavioShift3** [comment]
I think so. We added few informations when we finished Rowforge project. Now we have new project I will add more staff here.
Like how handle environments (prod, dev, stage) and more.

**Comment by michaelachrisco** [comment]
Sounds great, thanks @FlavioShift3.

**Comment by FlavioShift3** [comment]
But I think this issue can be closed. I will create another issue to keep NS updated

**Comment by michaelachrisco** [comment]
Agreed, I think the scope of this is finished by the `nativescript/README.md`. Closing.
