### ISSUE TITLE
Add Cloudfront set up script

### ISSUE THREAD

**Issue by carlosvargas** [Shift3/standards-and-practices#85]
I had written a script a few months ago that would set up the Cloudfront infrastructure needed to deploy an application (see #79). I'm creating this task so that I clean up the script and upload it to the repo.

**Comment by mwallert** [comment]
@carlosvargas I believe you got this finished right?

**Comment by carlosvargas** [comment]
Yeah, it's https://github.com/Shift3/standards-and-practices/blob/master/best-practices/development-tools/aws/cloudfront-set-up.sh

Not sure why I didn't close this when the PR was merged in, but I'll do it now.
