### ISSUE TITLE
Circle CI Integration quick-start for various platforms

### ISSUE THREAD

**Issue by Fleury14** [Shift3/standards-and-practices#94]
It would be cool to have a one-stop place for setting up CI with CircleCI for various environments. This includes:

- [x] React Native (with expo)
- [ ] React Native (CRNA)
- [x] Angular

Feel free to add more!

**Comment by zbyte64** [comment]
- [ ] Docker

Have a workflow that uses docker to build the application

Ultra-Gro & topflavorfarms both have this feature.

**Comment by michaelachrisco** [comment]
@Fleury14 Circleci + Angular is pretty easy now-days.

Oldish Example: https://medium.com/@brunopgalvao/building-an-angular-app-with-continuous-integration-on-circleci-41c68d668b12

Please with the newest version of Angular and it works.

**Comment by michaelachrisco** [comment]
Better yet, we can just steal: https://angular.io/guide/testing#configure-project-for-circle-ci

**Comment by michaelachrisco** [comment]
@Fleury14 Do you happen to know if we have any React Native projects with working CircleCI configurations? 

Im taking a look at: https://circleci.com/orbs/registry/orb/react-native-community/react-native and it involves a custom orb that seems to be what we are looking for.

**Comment by Fleury14** [comment]
Not that I'm aware of. I know the problem I ran into with Listing Alert was that I could never get basic tests to pass. I believe @kmausolf ran into a similar problem a while back. That said, there's probably been upgrades to RN since then.

**Comment by michaelachrisco** [comment]
@kmausolf and/or @Fleury14 What would be a good repo if we wanted to create a working circleci build/testing workflow? https://github.com/Shift3/rn-by-example
or would a new repo be the way to go? Something else? I feel like I want to take a stab at it and document the issues that we come across if we cant get it working.

**Comment by Fleury14** [comment]
Yeah, I think that's a great place to start.
