### ISSUE TITLE
Update new employee readme

### ISSUE THREAD

**Issue by ryekerjh** [Shift3/standards-and-practices#95]
With info related to giving props/explanations for workarounds in code

**Comment by ryekerjh** [comment]
@Shift3/pr-team Any of you who have been hired in the last year, can you just throw in 1 single suggestion for either `A.` an addition to our [New hire docs](https://github.com/Shift3/standards-and-practices#new-to-shift3) or `B.` Clarification on somethign you didn't see or wanted to see more of.
Thaaaaaanks 👍

**Comment by michaelachrisco** [comment]
@ryekerjh found a couple of new hire links that no longer go anywhere. 

Example is Acceptance Testing and Bug Reporting.
Ill do a quick pass over the docs and see what else I find. 

This is related to: #163

**Comment by michaelachrisco** [comment]
Quick pass reveals only two links are broken. PR should have the fix. wonder how many people have actually gone over the linked resources....

**Comment by ryekerjh** [comment]
@Shift3/pr-team Any of you who have been hired in the past 6 months, we would LOVE your input on the new hire resources. Your experience is invaluable in this time of tectonic shift and change in our work policies and organization.

**Comment by khiavdim** [comment]
It was daunting for the first few weeks but @kmausolf was able to do a walk through session of the standards and practices with me and @vinsonf a few weeks ago and that was able to clear up a LOT of confusing issues that was on my mind. That plus actually using Github was able to make me feel comfortable with the policies. I think if the new hires were able to get that walk through session, it would be super beneficial either before or a little bit after they start a project.

**Comment by michaelachrisco** [comment]
We had some really good PRs and boilerplate feedback for the last couple of weeks from new hires. Just wanted to acknowledge that.

If anyone has any suggestions, please let us know!

**Comment by michaelachrisco** [comment]
Im thinking we should revisit this with one of the new hires. Ill throw it on technical discussions later this week and attempt to get feedback!

**Comment by michaelachrisco** [comment]
I think this needs to get revisited. Anyone from @Shift3/pr-team want to chime in?

**Comment by thomwise** [comment]
Sounds like a good idea @michaelachrisco, did you want me to look into this with you at some point?

**Comment by michaelachrisco** [comment]
That would be awesome @thomascking. 

For now, I think we may need to review https://github.com/Shift3/standards-and-practices#new-to-bitwise and fill in/update the documentation.

**Comment by thomwise** [comment]
Okay. I'll take a look later on this afternoon. I'm not thomascking though. I feel like we get mixed up a lot.

**Comment by michaelachrisco** [comment]
Doh! I let GH autocorrect me. Super sorry about that! Ill fix.

**Comment by michaelachrisco** [comment]
I would say this is complete! We should revisit periodically and create a new issue. For now, this one is about 2 years old. Closing
